# Working on Dataset(1975-1999)

### i) Cleaning the data to seperate year,month,date,time,DST value and then storing them in form of a dictionary

In [1]:
# Here re stands for a regular expression, regex(sometimes called a rational expression), which is 
#a sequence of characters that define a search pattern.This pattern is used by string searching algorithms
#for "find" or "find and replace" operations on strings.
import re
final_data={}
count1=1;
with open('1975-1999.txt') as file: 
    lines =file.readlines() #reading the file line by line
    for line in lines:
        l=line.split() #splitting the line on spaces
        if len(l)==0:
            continue #if line is empty then continue
        #Date contains Year,month and date part
        Date=(re.findall(r'([\d.]+)-([\d.]+)-([\d.]+)',l[0]))
        #time comtains hour,min and sec where hour and min is always 00:00 so they are not needed to be extracted
        Time=(re.findall(r'([\d.]+):([\d.]+):([\d.]+)',l[1]))
        Date=list(Date[0])
        Time=list(Time[0])
        Year=Date[0]
        Month=Date[1]
        date=Date[2]
        Hour=Time[0]
        #The third and final part of the list contains dayofyear and DST Value part
        Dayofyear=l[2]
        value=l[3]
        #Storing the values in the form of dictionary
        final_data[count1]=({'DayofYear':Dayofyear,'Date':date,'Month':Month,'Year':Year,'Time(Hrs)':Hour,'Dst Index':value})
        count1=count1+1
    file.close()

### ii) Converting Dictionary in DataFrame

In [2]:
import pandas as pd
#pandas is an open source, library providing high-performance,easy-to-use data structures and data analysis tools for Python 
# DataFrame is tabular data structure with labeled axes (rows and columns).

df=(pd.DataFrame(final_data))#Converting a dictionary in a dataframe form

df=df.transpose()
df=(pd.DataFrame(df,columns=final_data[1].keys()))#Setting the column names

### iii) Displaying the Dataset

In [3]:
df

       DayofYear Date Month  Year Time(Hrs) Dst Index
1            001   01    01  1975        00     -7.00
2            001   01    01  1975        01     -9.00
3            001   01    01  1975        02    -10.00
4            001   01    01  1975        03    -11.00
5            001   01    01  1975        04    -12.00
6            001   01    01  1975        05     -9.00
7            001   01    01  1975        06     -8.00
8            001   01    01  1975        07     -7.00
9            001   01    01  1975        08    -14.00
10           001   01    01  1975        09    -13.00
11           001   01    01  1975        10    -10.00
12           001   01    01  1975        11     -9.00
13           001   01    01  1975        12    -10.00
14           001   01    01  1975        13     -8.00
15           001   01    01  1975        14     -5.00
16           001   01    01  1975        15     -5.00
17           001   01    01  1975        16     -8.00
18           001   01    01  1975        17     -8.00
19           001   01    01  1975        18     -7.00
20           001   01    01  1975        19     -9.00
21           001   01    01  1975        20     -9.00
22           001   01    01  1975        21     -7.00
23           001   01    01  1975        22     -7.00
24           001   01    01  1975        23    -10.00
25           002   02    01  1975        00    -10.00
26           002   02    01  1975        01    -10.00
27           002   02    01  1975        02     -8.00
28           002   02    01  1975        03     -6.00
29           002   02    01  1975        04     -5.00
30           002   02    01  1975        05     -2.00
...          ...  ...   ...   ...       ...       ...
219115       364   30    12  1999        18     28.00
219116       364   30    12  1999        19     24.00
219117       364   30    12  1999        20     18.00
219118       364   30    12  1999        21      6.00
219119       364   30    12  1999        22      6.00
219120       364   30    12  1999        23      7.00
219121       365   31    12  1999        00      0.00
219122       365   31    12  1999        01      3.00
219123       365   31    12  1999        02     -6.00
219124       365   31    12  1999        03     -8.00
219125       365   31    12  1999        04     -8.00
219126       365   31    12  1999        05    -13.00
219127       365   31    12  1999        06    -12.00
219128       365   31    12  1999        07    -17.00
219129       365   31    12  1999        08    -17.00
219130       365   31    12  1999        09    -17.00
219131       365   31    12  1999        10    -16.00
219132       365   31    12  1999        11    -13.00
219133       365   31    12  1999        12    -10.00
219134       365   31    12  1999        13    -22.00
219135       365   31    12  1999        14    -17.00
219136       365   31    12  1999        15    -12.00
219137       365   31    12  1999        16    -16.00
219138       365   31    12  1999        17    -24.00
219139       365   31    12  1999        18    -29.00
219140       365   31    12  1999        19    -32.00
219141       365   31    12  1999        20    -37.00
219142       365   31    12  1999        21    -34.00
219143       365   31    12  1999        22    -37.00
219144       365   31    12  1999        23    -50.00

[219144 rows x 6 columns]

### iv) Saving the dataframe in form of csv file with name 'DST(1975-1999).csv'

In [4]:
df.to_csv('DST(1975-1999).csv')

### v) Making respective data directories corresponding to the years

In [10]:
#The OS module in Python provides a way of using operating system dependent functionality. 
import platform
import os
sep=''
if platform.system()=='Windows':#Select seperator as per os 
    sep='\\'
else:
    sep='/'
#sepecifies directory path where we want to keep the files
cwd=os.getcwd()
dirpath=cwd+sep+'YearData'
#if directory path already has the folder then we skip this step
if not os.path.exists(dirpath):
        os.makedirs(dirpath)
for i in range(1975,2000):
    name=dirpath+sep+'DST_'+str(i)+'.csv'
    df[(df.Year ==str(i))].to_csv(name)#selecting that particular year from the data and converting to csv file format

### vi) Making respective data directories corresponding to the months

In [11]:
import os
dirpath1=cwd+sep+'MonthData'
if not os.path.exists(dirpath1):
        os.makedirs(dirpath1)
for i in range(1975,2000):
    dirpath2=cwd+sep+'MonthData'+sep+str(i)
    if not os.path.exists(dirpath2):
        os.makedirs(dirpath2)
    for j in range(1,13):
        mo=''
        if j<=9:
            mo='0'+str(j) #0-9 data is padded with a 0 at the beginning such that '1' is represented as '01'
        else:
            mo=str(j)
        #print(str(i)+" "+mo)
        name=dirpath2+sep+'DST_'+str(i)+'_'+mo+'.csv'
        (df[(df['Year']== str(i)) & (df['Month']==mo)]).to_csv(name)#selecting that particular year and month from the data and converting to csv file format

# Working on Dataset(2000-2018)

### i) Cleaning the data to seperate year,month,date,time,DST value and then storing them in form of a dictionary

In [12]:
import re
final_data={}
data_accyear={}
count1=1;
with open('2000-2018.txt') as file: 
    lines =file.readlines()
    for line in lines:
        l=line.split()
        if len(l)==0:
            continue
        Date=(re.findall(r'([\d.]+)-([\d.]+)-([\d.]+)',l[0]))
        Time=(re.findall(r'([\d.]+):([\d.]+):([\d.]+)',l[1]))
        Date=list(Date[0])
        Time=list(Time[0])
        Year=Date[0]
        Month=Date[1]
        date=Date[2]
        Hour=Time[0]
        Dayofyear=l[2]
        value=l[3]
        final_data[count1]=({'DayofYear':Dayofyear,'Date':date,'Month':Month,'Year':Year,'Time(Hrs)':Hour,'Dst Index':value})
        #data_accyear[count1][Year]=({'DayofYear':Dayofyear,'Date':date,'Month':Month,'Time(Hrs)':Hour,'Dst Index':value})
        count1=count1+1
    file.close()

### ii) Converting Dictionary in DataFrame

In [13]:
import pandas as pd
df=(pd.DataFrame(final_data))
df=df.transpose()
df=(pd.DataFrame(df,columns=final_data[1].keys()))

### iii) Displaying the Dataset

In [14]:
df

       DayofYear Date Month  Year Time(Hrs) Dst Index
1            001   01    01  2000        00    -45.00
2            001   01    01  2000        01    -37.00
3            001   01    01  2000        02    -37.00
4            001   01    01  2000        03    -41.00
5            001   01    01  2000        04    -45.00
6            001   01    01  2000        05    -39.00
7            001   01    01  2000        06    -38.00
8            001   01    01  2000        07    -35.00
9            001   01    01  2000        08    -38.00
10           001   01    01  2000        09    -30.00
11           001   01    01  2000        10    -23.00
12           001   01    01  2000        11    -21.00
13           001   01    01  2000        12    -22.00
14           001   01    01  2000        13    -23.00
15           001   01    01  2000        14    -21.00
16           001   01    01  2000        15    -22.00
17           001   01    01  2000        16    -21.00
18           001   01    01  2000        17    -23.00
19           001   01    01  2000        18    -24.00
20           001   01    01  2000        19    -27.00
21           001   01    01  2000        20    -25.00
22           001   01    01  2000        21    -26.00
23           001   01    01  2000        22    -28.00
24           001   01    01  2000        23    -28.00
25           002   02    01  2000        00    -24.00
26           002   02    01  2000        01    -23.00
27           002   02    01  2000        02    -24.00
28           002   02    01  2000        03    -24.00
29           002   02    01  2000        04    -25.00
30           002   02    01  2000        05    -28.00
...          ...  ...   ...   ...       ...       ...
159187       058   27    02  2018        18    -16.00
159188       058   27    02  2018        19    -15.00
159189       058   27    02  2018        20    -12.00
159190       058   27    02  2018        21     -6.00
159191       058   27    02  2018        22     -1.00
159192       058   27    02  2018        23      2.00
159193       059   28    02  2018        00      1.00
159194       059   28    02  2018        01      3.00
159195       059   28    02  2018        02      5.00
159196       059   28    02  2018        03      1.00
159197       059   28    02  2018        04     -2.00
159198       059   28    02  2018        05     -4.00
159199       059   28    02  2018        06     -8.00
159200       059   28    02  2018        07    -11.00
159201       059   28    02  2018        08    -11.00
159202       059   28    02  2018        09     -9.00
159203       059   28    02  2018        10    -10.00
159204       059   28    02  2018        11     -7.00
159205       059   28    02  2018        12     -5.00
159206       059   28    02  2018        13     -4.00
159207       059   28    02  2018        14     -3.00
159208       059   28    02  2018        15     -1.00
159209       059   28    02  2018        16     -4.00
159210       059   28    02  2018        17     -6.00
159211       059   28    02  2018        18     -6.00
159212       059   28    02  2018        19     -5.00
159213       059   28    02  2018        20     -2.00
159214       059   28    02  2018        21     -1.00
159215       059   28    02  2018        22      2.00
159216       059   28    02  2018        23      4.00

[159216 rows x 6 columns]

### iv) Saving the dataframe in form of csv file with name 'DST(2000-2018).csv'

In [15]:
df.to_csv('DST(2000-2018).csv')

### v) Making respective data directories corresponding to the years

In [16]:
import os
dirpath=cwd+sep+'YearData'
if not os.path.exists(dirpath):
        os.makedirs(dirpath)
for i in range(2000,2019):
    name=dirpath+sep+'DST_'+str(i)+'.csv'
    df[(df.Year ==str(i))].to_csv(name)

### vi) Making respective data directories corresponding to the months

In [17]:
import os
dirpath1=cwd+sep+'MonthData'
if not os.path.exists(dirpath1):
        os.makedirs(dirpath1)
for i in range(2000,2019):
    dirpath2=cwd+sep+'MonthData'+sep+str(i)
    if not os.path.exists(dirpath2):
        os.makedirs(dirpath2)
    for j in range(1,13):
        mo=''
        if j<=9:
            mo='0'+str(j)
        else:
            mo=str(j)
        #print(str(i)+" "+mo)
        if i==2018 and j==3 :
            break
        name=dirpath2+sep+'DST_'+str(i)+'_'+mo+'.csv'
        (df[(df['Year']== str(i)) & (df['Month']==mo)]).to_csv(name)